<a href="https://colab.research.google.com/github/salviyas/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
zeros=np.zeros((3,3))
zeros


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [6]:
for i in range(0,10,2):
    print(i)

0
2
4
6
8


In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0,1000,4)

array([   0.        ,  333.33333333,  666.66666667, 1000.        ])

In [13]:
arr.shape

(10,)

In [14]:
arr.size

10

In [15]:
arr.dtype

dtype('int64')

In [18]:
arr[9]

10

In [19]:
arr[1:3]

array([2, 3])

In [21]:
arr[3]=20
arr

array([10,  2,  3, 20,  5,  6,  7,  8,  9, 10])

In [32]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr1/arr2

array([0.25, 0.4 , 0.5 ])

In [29]:
arr3=arr1*arr2
arr3

array([ 4, 10, 18])

In [33]:
arr +5

array([15,  7,  8, 25, 10, 11, 12, 13, 14, 15])

In [35]:
np.sqrt(arr)

array([3.16227766, 1.41421356, 1.73205081, 4.47213595, 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [36]:
np.exp(arr)

array([2.20264658e+04, 7.38905610e+00, 2.00855369e+01, 4.85165195e+08,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [49]:
arr4=np.arange(10).reshape(2,5)
arr4


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
arr5=arr.ravel()
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [71]:
arr6=np.vstack((arr1,arr2))
arr6

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [51]:
arr4[0,2]

2

In [53]:
arr4[:,1:3]

array([[1, 2],
       [6, 7]])

In [57]:
arr5.sum()

45

In [63]:
arr5[9]=arr5.mean()
print(arr5)

[0 1 2 3 4 5 6 7 8 4]


In [64]:
arr5.sort()
arr5

array([0, 1, 2, 3, 4, 4, 5, 6, 7, 8])

In [65]:
arr5.max()

8

In [66]:
arr5.min()

0

In [67]:
arr.std()

2.449489742783178

In [78]:
print(arr6)
arr6.sum(axis=0)
arr6.sum(axis=1)

[[1 2 3]
 [4 5 6]]


array([ 6, 15])